# repositories/interfaces.py
from __future__ import annotations

from typing import Protocol, Optional, List
from domain.models import User, Task, TaskNote


class IUserRepository(Protocol):
    def create(self, user: User) -> User: ...
    def find_by_username(self, username: str) -> Optional[User]: ...
    def find_by_id(self, user_id: int) -> Optional[User]: ...
    def update_salt(self, user_id: int, salt: bytes) -> None: ...


class ITaskRepository(Protocol):
    def create(self, task: Task) -> Task: ...
    def find_by_id(self, task_id: int) -> Optional[Task]: ...
    def find_all_by_owner(self, owner_id: int) -> List[Task]: ...
    def update(self, task: Task) -> Task: ...
    def delete(self, task_id: int) -> None: ...
    def mark_completed(self, task_id: int) -> None: ...


class INoteRepository(Protocol):
    def create(self, note: TaskNote) -> TaskNote: ...
    def find_by_id(self, note_id: int) -> Optional[TaskNote]: ...
    def find_by_task(self, task_id: int) -> List[TaskNote]: ...
    def update(self, note: TaskNote) -> TaskNote: ...
    def delete(self, note_id: int) -> None: ...
